[package]
name = "aura_test"
version = "0.1.0"
edition = "2021"

[dependencies]
# client-generic sudah otomatis include: client + api-types + tonic 0.14
aura_api_client = {
    git = "https://github.com/in-aura-we-trade/aura_api_client.git",
    features = ["client-generic"]
}

tokio      = { version = "1.38", features = ["full"] }
tonic      = "0.14"   # harus sama dengan versi yang dipakai aura_api_client
log        = "0.4"
env_logger = "0.10"
